### ISSUE TITLE
[Google] unable to open crashbin

### ISSUE THREAD

**Issue by Fitblip** [OpenRCE/sulley#24]
**What steps will reproduce the problem?**
1. done fuzzing
2. use crashbin_explorer.py 
3. ERROR

**What is the expected output? What do you see instead?**
D:\ZFTEST\sulley\utils>crashbin_explorer.py audits\war-ftp.crashbin
unable to open crashbin: 'audits\war-ftp.crashbin'.

why?

**What version of the product are you using? On what operating system?**
sulley-stable-rev157  WINDOWS XP3

**Please provide any additional information below.**
Is there something required?

**Comment by all3g** [comment]
```
C:\Fuzzing\sulley>python utils\crashbin_explorer.py pcmanftpd2_crashbin
unable to open crashbin: 'pcmanftpd2_crashbin'.

C:\Fuzzing\sulley>ver

Microsoft Windows XP [Version 5.1.2600]
```

Please check the file - [pcmanftpd2_crashbin.zip](https://github.com/OpenRCE/sulley/files/169510/pcmanftpd2_crashbin.zip)
