### ISSUE TITLE
[Google] struct.error: unpack requires a string argument of length 1

### ISSUE THREAD

**Issue by Fitblip** [OpenRCE/sulley#25]
**What steps will reproduce the problem?**
1. When trying to fuzz binary files with custom request

**What is the expected output? What do you see instead?**
seems value       = struct.unpack(endian + "B", value)[0] in primitives.py will not unpack binary data sent.
Custom request is attached.

 > File "C:\sulley\primitives.py", line 807, in __init__
    value       = struct.unpack(endian + "B", value)[0]
struct.error: unpack requires a string argument of length 1

Attachments:
[bmp.py](https://gist.github.com/2380651)

**Comment by SteveJM** [comment]
I'm not sure this is really a problem.
In bmp.py, the integer values supplied to s_dword, etc should not be quoted as strings. Then Python will treat as integer values.

**Comment by SteveJM** [comment]
Here is a modified bmp.py. The dword values unquoted. Random data for the headers and foxed binary for the pixels (given that these would be raw binary, fizzing of the data is very likely pointless).
-----
from sulley import *
 
s_initialize("bug.bmp")
s_string('BM') #signature de root
s_dword(2046820608, endian='<') #file_size de root
s_random(00000000, min_length=4, max_length=4) # reserved de root
s_dword(2046820352, endian='<') #data_start de root
s_dword(1811939328, endian='<') #header_size de header
s_dword(2147483648, endian='<') #width de header
s_dword(2147483648, endian='<') #height de header
s_word(256, endian='<') #nb_plan de header
s_word(8192, endian='<') #bpp de header
s_dword(50331648, endian='<') #compression de header
s_dword(256, endian='<') #image_size de header
s_dword(302710784, endian='<') #horizontal_dpi de header
s_dword(302710784, endian='<') #vertical_dpi de header
s_dword(0, endian='<') #used_colors de header
s_dword(0, endian='<') #important_color de header
s_dword(65280, endian='<') #red_mask de header
s_dword(16711680, endian='<') #green_mask de header
s_dword(4278190080, endian='<') #blue_mask de header
s_dword(255, endian='<') #alpha_mask de header
s_dword(16777216, endian='<') #color_space de header
s_random(000000000000000001000000, min_length=12, max_length=12) # red_primary de header
s_random(000000000000000001000000, min_length=12, max_length=12) # green_primary de header
s_random(000000000000000001000000, min_length=12, max_length=12) # blue_primary de header
s_dword(0, endian='<') #gamma_red de header
s_dword(0, endian='<') #gamma_green de header
s_dword(0, endian='<') #gamma_blue de header
s_binary("fffffffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefeffff") # line[127] de pixels
s_binary("fffffffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefeffff") # line[126] de pixels
s_binary("fffffffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefeffff") # line[125] de pixels
s_binary("fffffffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefeffff") # line[124] de pixels
s_binary("fffffffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefeffff") # line[123] de pixels
s_binary("fffffffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefeffff") # line[122] de pixels
s_binary("fffffffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefefffffefeffff020d73ff020d73ff020d73ff020d73ff020d73ff020d73ff020d73ff020d73ff020d73ff020d73ff020d73ff020d73ff020d73ff020d73ff020d73ff020d73ff020d73ff020d73ff020d73ff020d73ff020d73ff020d73ff030d73ff030e70ff03106eff031171ff020c5bff030d56ff041268ff03105eff03105cff041263ff041362ff031053ff030f4cff041258ff06175eff020c4aff020b4eff010549ff030d55ff030660ff000444ff091756ff141c72ff0b115fff142f56ff37568dff6986aeff44699eff243e83ff040c3bfe00000fff000000ff000000ff000000ff000000ff000000ff000000ff000018ff00000aff000104ff000004ff000000ff000007ff00010fff000607ff000307ff000107ff00030cff020415ff000007ff00010aff0208") # line[121] de pixels

**Comment by SteveJM** [comment]
I believe that this issue can now be closed.

**Comment by Fitblip** [comment]
Agreed. Thanks @SteveJM!
