### ISSUE TITLE
How to Install Sulley on Linux (Ubuntu 12.04)

### ISSUE THREAD

**Issue by ghost** [OpenRCE/sulley#51]
Hi,

I have been using Sulley for about a week and a half now on Windows 7 and absolutely love it!  Now I am trying to figure out how to install Sulley on my Ubuntu 12.04 machine and cannot find any good tutorials online.  Are there any tutorials online that anyone knows of or can somebody please help me figure out how to install Sulley on my Linux machine?  This would be a life saver.

Thanks a lot,
-4leaf

**Comment by JkShah1992** [comment]
http://www.talesofacoldadmin.com/vdb/vdb_20120806.zip. this link is not available. So how should i download this vTrace?

**Comment by fouzhe** [comment]
Hi, all
http://www.talesofacoldadmin.com/vdb/vdb_20120806.zip. this link is not available. So how should i download this vTrace?
