### ISSUE TITLE
Rendering of group references

### ISSUE THREAD

**Issue by theliberator** [OpenRCE/sulley#57]
I initialize adata model as beneath:

s_initialize("DM2")
s_group("group", values=["A_", "B_", "C_", "D_"])
if s_block_start("BLOCK1"):
    s_string("string1_", name="string1")
    s_block_end()
if s_block_start("BLOCK2", group="group"):
    s_string("string2_", name="string2")
    s_block_end()

Then I call 's_render()' and check the value. What I expected was:

'string1_A_string2_'

instead I got:

'A_string1_string2_'

It seems to me that the group reference of BLOCK2 is not rendered at all, because the result is the same, when I remove the group reference from BLOCK2.

**Comment by SteveJM** [comment]
It looks like this can be closed.
